import React from "react";

const Terms = () => (
  <div className="max-w-4xl mx-auto px-4 py-12">
    <h1 className="text-3xl font-bold mb-6 text-accent">Terms & Conditions</h1>
    <p className="mb-4">By using Gridspark Solutions’ website and AI demos, you agree to abide by these terms. Please review carefully before accessing our services.</p>
    <h2 className="text-xl font-semibold mt-6 mb-2">Acceptable Use</h2>
    <ul className="list-disc pl-6 mb-4">
      <li>You agree not to use our services for unlawful purposes.</li>
      <li>Content generated by AI demos is for example/demo purposes and may not substitute professional advice.</li>
    </ul>
    <h2 className="text-xl font-semibold mt-6 mb-2">Intellectual Property</h2>
    <ul className="list-disc pl-6 mb-4">
      <li>All content, branding, and technology are property of Gridspark Solutions unless otherwise indicated.</li>
      <li>You may not reproduce, redistribute, or misuse site material.</li>
    </ul>
    <h2 className="text-xl font-semibold mt-6 mb-2">Changes</h2>
    <ul className="list-disc pl-6 mb-4">
      <li>Terms may change with updates. Continued use means acceptance of changes.</li>
    </ul>
    <p className="text-xs mt-6 text-gray-500">Contact us for any questions about these terms: <a href="mailto:info@gridspark.com" className="text-accent">info@gridspark.com</a></p>
  </div>
);

export default Terms;
